config/routes.rb
Rails.application.routes.draw do
  root 'homepages#index'

  resources :homepages

end

app/models/attack.rb
class Attack < ActiveRecord::Base
end

app/models/homepage.rb
class Homepage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController

  def index
    @homepages = Homepage.last
  end

  def new
    @homepage = Homepage.new
  end

  def create
    @homepage = Homepage.create(homepages_params)
    if @homepage.valid?
      redirect_to root_path
    else
      render :new, :status => :unprocessable_entity
    end
  end

  private

  def homepages_params
    params.require(:homepage).permit(:name, :animal, :size)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/views/homepages/index.html.erb
<div class="center-me">
  <h1 class="headline">
      <span class="view">View</span>
      <span class="the">the</span>
      <span class="red">r</span>
      <span class="orange">a</span>
      <span class="yellow">i</span>
      <span class="green">n</span>
      <span class="blue">b</span>
      <span class="indigo">o</span>
      <span class="violet">w!</span>
  </h1>
  <%= button_to "Click me!", new_homepage_path, :method => :get %>
</div>
<br>
<div class="center-me">
  <% if @homepages.present? %>
    <%= @homepages.name %>
    was here and likes
    <%= @homepages.animal %>s.
  <% end %>
</div>

app/views/homepages/new.html.erb
<br>
<div class="the-form">
  <h2>Are you ready?</h2>
  <%= simple_form_for @homepage do |f| %>
    <%= f.input :name, :label => "What is your name: " %>
    <br>
    <%= f.input :animal, :label => "Your favorite animal: " %>
    <br>
    <%= f.submit "Lets Go!" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>